# Generated by Django 3.1 on 2020-09-23 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mappy', '0002_remove_coord_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coord',
            name='id',
        ),
        migrations.AddField(
            model_name='coord',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coord',
            name='object_label',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
