# Generated by Django 3.1 on 2020-09-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappy', '0004_auto_20200923_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coord',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
